version: '3.7'

services:
  conf_service:
    build: ./service
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./service/:/src/
    ports:
      - 8001:8000
    environment:
      - POSTGRES_USER=conf_db_username
      - POSTGRES_PASSWORD=conf_db_password
      - POSTGRES_DB=conf_db_dev

      - POSTGRES_USER_T=conf_db_username_t
      - POSTGRES_PASSWORD_T=test
      - POSTGRES_DB_T=conf_db_dev_t


      # - DATABASE_URI=postgresql://conf_db_username:conf_db_password@conf_db/conf_db_dev
      # - T_URI=postgresql://conf_db_username_t:test@conf_db_test:5433/conf_db_dev_t
    depends_on:
      - conf_db
      - conf_db_test

  conf_db:
    image: postgres:12.1-alpine
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - postgres_data_conf:/var/lib/postgresql/data/
    environment:
      - POSTGRES_MULTIPLE_DATABASES: conf_db_dev,conf_db_dev_t
      - POSTGRES_USER=conf_db_username
      - POSTGRES_PASSWORD=conf_db_password
      - POSTGRES_DB=conf_db_dev
    ports:
      - 5432:5432
    expose:
      - 5432

  conf_db_test:
    image: postgres:12.1-alpine
    volumes:
      - postgres_db_test:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=conf_db_username_t
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=conf_db_dev_t
      - T_URI=postgresql://conf_db_username_t:test@conf_db_test:5433/conf_db_dev_t
    ports:
      - 5434:5432

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - conf_service

volumes:
  postgres_data_conf:
  postgres_db_test: