version: '3.7'

services:
  conf_service:
    build: ./config-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./config-service/:/app/
    ports:
      - 8001:8000
    environment:
      - POSTGRES_USER=conf_db_username
      - POSTGRES_PASSWORD=conf_db_password
      - POSTGRES_DB=conf_db_dev
      - DATABASE_URI=postgresql://conf_db_username:conf_db_password@conf_db/conf_db_dev
     # - T_URI=postgresql://conf_db_username_t:test@conf_db_test:5433/conf_db_dev_t
    depends_on:
      - conf_db

  conf_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_conf:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=conf_db_username
      - POSTGRES_PASSWORD=conf_db_password
      - POSTGRES_DB=conf_db_dev
    ports:
    - "5432:5432"
    expose:
      - 5432

  conf_db_test:
    image: postgres:12.1-alpine
    # volumes:
    #   - postgres_db_test:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=conf_db_username_t
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=conf_db_dev_t
      - T_URI=postgresql://conf_db_username_t:test@conf_db_test:5433/conf_db_dev_t
    ports:
    - "5433:5432"
    expose:
      - 5433

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - conf_service

volumes:
  postgres_data_conf:
  postgres_db_test: