version: '3.8'

services:
  conf_service:
    build: ./service
    command: python -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./service/app:/app/
    ports:
      - 8001:8000
    environment:
      - POSTGRES_USER=conf_db_username
      - POSTGRES_PASSWORD=conf_db_password
      - POSTGRES_DB=conf_db_dev
      #test db name is "test". If you want to change this name, you need to update the init.sql file also, in the postgres folder
      - POSTGRES_DB_T=test
    depends_on:
      - conf_db

  conf_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_conf:/var/lib/postgresql/data/
      - ./postgres_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=conf_db_username
      - POSTGRES_PASSWORD=conf_db_password
      - POSTGRES_DB=conf_db_dev
    ports:
      - "5432:5432"
    expose:
      - 5432

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - conf_service

volumes:
  postgres_data_conf: