version: '3.7'

services:
  conf_service:
    build: ./config-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./config-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://conf_db_username:conf_db_password@conf_db/conf_db_dev
    depends_on:
      - conf_db

  conf_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_conf:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=conf_db_username
      - POSTGRES_PASSWORD=conf_db_password
      - POSTGRES_DB=conf_db_dev

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - conf_service

volumes:
  postgres_data_conf: